Add a presubmit check to ensure that the combined schemas are updated (#235)

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -33,6 +33,14 @@ jobs:
       
       - name: Install dependencies
         run: npm ci
+
+      - name: Check combined schema
+        run: |
+          npm run build:openapi
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "Error: Build produced uncommitted changes in openapi.yaml. Please rerun npm run build:openapi and commit the changes to the combined schema"
+            exit 1
+          fi
       
       - name: Lint
-        run: npm run lint 
+        run: npm run lint:openapi 
